version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - /home/vagrant/data/mysql:/var/lib/mysql
      

  spring_app:
    image: devopskaddem
    container_name: devopskaddem
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    
