version: "3"

volumes:
  db:

services:
  kadem:
    image: mohameddhibi/kaddem:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - 8089:8089
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kaddem?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD: ""   # Set your password here (or leave it empty if no password)

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE: kaddem
      - MYSQL_ROOT_PASSWORD: ""   # Set your password here (or leave it empty if no password)
      - MYSQL_ALLOW_EMPTY_PASSWORD: TRUE
